# Generated by Django 3.2 on 2023-10-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='atarctic-banner'),
        ),
    ]
