# Generated by Django 3.2 on 2023-05-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230513_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='background_video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
