# Generated by Django 3.2 on 2023-06-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
