# Generated by Django 3.2 on 2023-06-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
