# Generated by Django 3.2 on 2024-03-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
    ]
