# Generated by Django 3.2 on 2023-10-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('password', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[(0, 'DELETED'), (1, 'ACTIVE'), (2, 'INACTIVE'), (3, 'BLOCKED')], default=1, max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
