# Generated by Django 3.2 on 2024-03-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
