# Generated by Django 3.2 on 2023-06-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
