# Generated by Django 3.2 on 2024-03-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_partner_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('media', models.FileField(blank=True, upload_to='partner-media')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.partner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
