# Generated by Django 3.2 on 2024-03-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_partnermedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerMedia',
        ),
    ]
